[locness_dash]
# Path to the SQLite database file
# Example: db_file_path = "underway_data.db"
db_file_path = "underway_data.db"

# Default resampling interval for the dropdown
# Options: "1min", "10min", "1H", etc.
default_resampling = "1min"

# Update interval in seconds for the periodic data refresh
update_interval = 10
