[project]
name = "locness-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.1.1",
    "dash-bootstrap-components>=2.0.3",
    "gunicorn>=23.0.0",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]
